version: '3.8'
services:
  yb-master:
      image: yugabytedb/yugabyte:latest
      container_name: yb-master-n1
      command: [ "/home/yugabyte/bin/yb-master",
                "--fs_data_dirs=/mnt/master",
                "--master_addresses=yb-master-n1:7100",
                "--rpc_bind_addresses=yb-master-n1:7100",
                "--replication_factor=1"]
      ports:
      - "7000:7000"
      environment:
        SERVICE_7000_NAME: yb-master

  yb-tserver:
      image: yugabytedb/yugabyte:latest
      container_name: yb-tserver-n1
      command: [ "/home/yugabyte/bin/yb-tserver",
                "--fs_data_dirs=/mnt/tserver",
                "--start_pgsql_proxy",
                "--rpc_bind_addresses=yb-tserver-n1:9100",
                "--tserver_master_addrs=yb-master-n1:7100"]
      ports:
      - "9042:9042"
      - "5433:5433"
      - "9000:9000"
      environment:
        SERVICE_5433_NAME: ysql
        SERVICE_9042_NAME: ycql
        SERVICE_6379_NAME: yedis
        SERVICE_9000_NAME: yb-tserver
      depends_on:
      - yb-master

  postgres:
    image: postgres:latest
    container_name: postgres-container
    ports:
      - 55432:5432/tcp
    environment:
      POSTGRES_DB: test
      POSTGRES_PASSWORD: testpassword

  mysql:
    image: mysql:latest
    restart: always
    ports:
    - "3306:3306"
    expose:
    - 3306
    environment:
      MYSQL_DATABASE: test
      MYSQL_USER: root
      MYSQL_ALLOW_EMPTY_PASSWORD: yez
    volumes:
      - my-db:/var/lib/mysql

  mariadb:
    image: mariadb
    restart: always
    environment:
      MYSQL_DATABASE: test
      MYSQL_USER: tester
      MYSQL_PASSWORD: testpassword
      MYSQL_ROOT_PASSWORD: testpassword
    ports:
    - "3307:3306"
    expose:
    - 3306

volumes:
  yb-master-data-1:
  yb-tserver-data-1:
  my-db: